export interface User {
  id: number,
  id_str: string,
  name: string,
  screen_name: string,
  location: string | null,
  url: string | null,
  description: string | null,
  followers_count: number,
  friends_count: number,
  listed_count: number,
  favourites_count: number,
  statuses_count: number,
  created_at: string,
  profile_image_url_https: string,
  profile_banner_url: string,
}

export interface Tweet {
  created_at: string,
  id: number,
  id_str: number,
  text: string,
  source: string,
  truncated: boolean,
  in_reply_to_status_id: number | null,
  in_reply_to_status_id_str: string | null,
  in_reply_to_user_id: number | null,
  in_reply_to_user_id_str: string | null,
  in_reply_to_screen_name: string | null,
  user: User,
  reply_count: number,
  retweet_count: number,
  favorite_count: number,
  favorited: boolean,
  retweeted: boolean,
}